apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: owzz8a5jg-go 
  janus-idp.io/tekton: owzz8a5jg-go
  backstage.io/kubernetes-id: owzz8a5jg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: owzz8a5jg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml