apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: owzz8a5jg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: owzz8a5jg-go 
  name: owzz8a5jg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: owzz8a5jg-go 
