apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: owzz8a5jg-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0ab37713bc.g16h.p3.openshiftapps.com/rhtap/rhtap-qe:1e4305b4085389d86c3b0565d34ed696441da2b6@sha256:274bfa33131efd35b37413917b5bf55d4b7d7ba97e0b47e6439f71553cb4e554
          name: container-image
